### ISSUE TITLE
Deployment uses hostNetwork: true

### ISSUE THREAD

**Issue by sfb103** [sfb103/simple-k8s-hdhomerun-record#5]
Currently the hdhomerun record engine deployment uses ```hostNetwork: true```. This was the only way to allow the process to be discoverable by [http://my.hdhomerun.com](http://my.hdhomerun.com).  Preferrably, the correct ports could be forwarded and no longer require ```hostNetwork: true```.

Here is a sample yaml file to start with:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdhomerun-record
  labels:
    name: hdhomerun-record
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hdhomerun-record
  template:
    metadata:
      labels:
        name: hdhomerun-record
    spec:
      volumes:
      - hostPath:
          path: /mnt/disks/recordings/HDHomeRun
        name: recordings
      containers:
      - name: hdhomerun-record
        image: argos:5000/hdhomerun-record
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /HDHomeRun
          name: recordings
        livenessProbe:
          tcpSocket:
            port: 46759
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hdhomerun-record
  labels:
    name: hdhomerun-record
spec:
  ports:
  - name: listen-port
    protocol: "TCP"
    port: 46759
    targetPort: 46759
    nodePort: 46759
  - name: discovery-port
    protocol: "UDP"
    port: 65001
    targetPort: 65001
    nodePort: 65001
  selector:
    name: hdhomerun-record
  type: NodePort
```
